# Site settings
title: noppelab
email: noppelabs@gmail.com
url: https://noppelab.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "iOS,Swift"
skills: "iOS apps developer"
meta_author: Hirano Tomoya

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1C304A #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 323232 #FD6E8A
  secondary-dark: 282828 #A2122F

# Footer settings
footer:
  copyright: noppelab.com
  social: Social Links

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/noppefoxwolf
  - title: github
    url: https://github.com/noppefoxwolf
  - title: search
    url: https://qiita.com/noppefoxwolf

# Postal address (add as many lines as necessary)
address:
  # - line: JP

# Credits content
# credits: ''

# Build settings
markdown: kramdown
permalink: pretty
